### ISSUE TITLE
还是能匹配到rpg

### ISSUE THREAD

**Issue by redaliez** [deximy/SteamServerFilter#2]
如题，尝试快速匹配的时候还是大概率匹配到RPG的。是不是匹配这个问题无法解决啊？ 

[Uploading 2023-03-03.log…]()

**Comment by redaliez** [comment]
[2023-03-03.log](https://github.com/deximy/SteamServerFilter/files/10883196/2023-03-03.log)

**Comment by deximy** [comment]
匹配到的RPG名字符合已添加的表达式吗？IP是多少？

**Comment by deximy** [comment]
看了一下你上传的log中的最后两次记录，倒数第二次快速匹配没看出什么问题：

> 2023-03-03 22:46:24.141 DEBUG Detected an unknown endpoint: 192.168.254.253:20031
> 2023-03-03 22:46:26.830 DEBUG Block incoming traffic from an endpoint in black list: 113.103.59.38:777
> 2023-03-03 22:46:29.172 DEBUG Block outcoming traffic to an endpoint in black list: 123.113.149.221:20031
> 2023-03-03 22:46:30.173 DEBUG Detected an unknown endpoint: 192.168.254.253:20031
> 2023-03-03 22:46:35.205 DEBUG Block outcoming traffic to an endpoint in black list: 123.113.149.221:20031
> 2023-03-03 22:46:36.206 DEBUG Detected an unknown endpoint: 192.168.254.253:20031
> 2023-03-03 22:46:41.205 DEBUG Block outcoming traffic to an endpoint in black list: 123.113.149.221:20031
> 2023-03-03 22:46:42.206 DEBUG Detected an unknown endpoint: 192.168.254.253:20031
> 2023-03-03 22:46:47.238 DEBUG Block outcoming traffic to an endpoint in black list: 123.113.149.221:20031
> 2023-03-03 22:46:48.239 DEBUG Detected an unknown endpoint: 192.168.254.253:20031
> 2023-03-03 22:46:53.271 DEBUG Block outcoming traffic to an endpoint in black list: 123.113.149.221:20031
> 2023-03-03 22:46:54.271 DEBUG Detected an unknown endpoint: 192.168.254.253:20031
> 2023-03-03 22:46:59.303 DEBUG Block outcoming traffic to an endpoint in black list: 123.113.149.221:20031
> 2023-03-03 22:47:00.304 DEBUG Detected an unknown endpoint: 192.168.254.253:20031
> 2023-03-03 22:47:05.305 DEBUG Block outcoming traffic to an endpoint in black list: 123.113.149.221:20031
> 2023-03-03 22:47:06.306 DEBUG Detected an unknown endpoint: 192.168.254.253:20031
> 2023-03-03 22:47:11.337 DEBUG Block outcoming traffic to an endpoint in black list: 123.113.149.221:20031
> 2023-03-03 22:47:12.337 DEBUG Detected an unknown endpoint: 192.168.254.253:20031

从log中能看出这是一次针对快速匹配的行为记录，尝试连接到的公网endpoint是123.113.149.221:20031，内网endpoint是192.168.254.253:20031（steam的matchmaking机制是同时会以公网和内网的方式尝试连接到目标lobby），其中所有针对公网endpoint的请求均被软件拦截（即10次`Block outcoming traffic to an endpoint in black list: 123.113.149.221:20031`的记录），十次针对内网endpoint的请求全部无回应，这次阻止应该是成功了的。

接下来是最后一次快速匹配的记录：

> 2023-03-03 22:47:32.456 DEBUG Detected an unknown endpoint: 121.62.22.130:8069
> 2023-03-03 22:47:55.475 INFO  Block server with name: ﻿[趣味]-弑神巅峰

这里并没有后续主动阻止连接的记录，你是不是还在用1.1版？主动侦测并阻止连接是1.2版的新功能。

**Comment by redaliez** [comment]
1.2
![image](https://user-images.githubusercontent.com/57378016/222909677-f37843e8-65c3-4e93-9188-f46bcfeab168.png)
难道说是这个拦截功能还不够强力？反正我现在匹配还是一堆RPG

**Comment by deximy** [comment]
按以下步骤发一次完整的记录：

1. 更新至1.3版
2. 退出正在运行的程序
3. 删除`Logs`文件夹内的全部内容
4. 启动程序
5. 打开游戏进行快速匹配，直到出现屏蔽失败的RPG服务器为止
6. 退出程序
7. 上传log文件

**Comment by redaliez** [comment]
[2023-03-05.log](https://github.com/deximy/SteamServerFilter/files/10891552/2023-03-05.log)

**Comment by deximy** [comment]
该问题可能在https://github.com/deximy/SteamServerFilter/commit/f371a1cebb4d20e0cd75765eec1f0de3e842201f 中被修复，详情请参考commit message。
请[下载最新构建的程序](https://github.com/deximy/SteamServerFilter/releases/tag/1.4)重新测试并反馈结果，谢谢。

**Comment by redaliez** [comment]
按照你的意思测试了下，发现直接全部屏蔽了，啥服务器都进不去，匹配功能废掉了。删掉.*?
Valve倒是可以
[2023-03-06.log](https://github.com/deximy/SteamServerFilter/files/10892932/2023-03-06.log)

**Comment by deximy** [comment]
那个是我测试的时候快速屏蔽所有服务器用的，正式发布的时候会去掉。没问题的话就close了。
