### ISSUE TITLE
为啥有这个拦截原因？DEBUG Block incoming traffic from an endpoint in black list，之前好像没有？

### ISSUE THREAD

**Issue by QAQ-Huaxia** [deximy/SteamServerFilter#3]

**Comment by deximy** [comment]
DEBUG状态下的提示，代表程序拦截了一个从黑名单服务器发送到本地的数据包。这个是最新版在Debug模式下才会有的提示，方便定位问题，之前你可能是用的旧版，旧版是没有这个提示的。~~当然也有可能是你之前没在意这个提示。~~

**Comment by QAQ-Huaxia** [comment]
可以把这两个服务器地址从黑名单中移出吗？101.200.45.240和39.105.101.53，这个是属于求生之路6666这个组的服务器，不是流氓或者rpg服务器。是正常纯净的服务器，不应该在拦截范围。您可以进去体验一下
![Snipaste_2023-05-29_14-13-35](https://github.com/deximy/SteamServerFilter/assets/67990248/548a0eaa-fe0c-4fbb-a18a-78ef76376819)

**Comment by deximy** [comment]
程序没有强制规定任何规则，所有屏蔽规则均由玩家自行添加，与本人无关。

**Comment by QAQ-Huaxia** [comment]
![Snipaste_2023-05-29_23-27-02](https://github.com/deximy/SteamServerFilter/assets/67990248/ebeb3b45-58cd-49db-bbfb-75570d36bb3f)
但我的规则就这些，好像并没有符合的，而且符合规则里面的话会显示原因Block server with name吧？

**Comment by QAQ-Huaxia** [comment]
![Snipaste_2023-05-29_23-52-18](https://github.com/deximy/SteamServerFilter/assets/67990248/129f0b22-3764-4b03-97d9-37844b92ba21)

当然我并不了解这些，只是问问哈

**Comment by deximy** [comment]
只有第一次会显示Block server with name，可以查一下记录里面有没有，或者把完整记录上传上来。

**Comment by QAQ-Huaxia** [comment]
[Logs.zip](https://github.com/deximy/SteamServerFilter/files/11594761/Logs.zip)

5分钟的记录+我所使用的规则，麻烦大佬看看

**Comment by deximy** [comment]
你给的log里没有包含101.200.45.240和39.105.101.53这两个服务器，也没有查到命中你给的服务器名的记录。

**Comment by QAQ-Huaxia** [comment]
抱歉抱歉，软件并没有拦截，我只顾看端口了，只看端口相似了，没看仔细IP，就过来问了，sb了，抱歉打扰了
